---
- name: Import EPEL, Remi and RPMForge GPG keys
  rpm_key: "key={{ item }} state=present"
  with_items:
  - "https://fedoraproject.org/static/0608B895.txt"
  - "http://rpms.famillecollet.com/RPM-GPG-KEY-remi"
  - "http://apt.sw.be/RPM-GPG-KEY.dag.txt"

- name: Install EPEL, Remi, RPMForge and Nginx repos
  command: "rpm -Uvh --force {{ item.href }} creates={{ item.creates }}"
  with_items:
  - {
    href: "http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm",
    creates: "/etc/yum.repos.d/epel.repo"
  }
  - {
    href: "http://rpms.famillecollet.com/enterprise/remi-release-6.rpm",
    creates: "/etc/yum.repos.d/remi.repo"
  }
  - {
    href: "http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm",
    creates: "/etc/yum.repos.d/rpmforge.repo"
  }
  - {
    href: "http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm",
    creates: "/etc/yum.repos.d/nginx.repo"
  }

- name: Manualy update EPEL repo until it's fixed
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 644
  with_items:
  - {
    src: "yum.repos.d/epel.repo",
    dest: "/etc/yum.repos.d/epel.repo"
  }

- name: Remove unused packages
  yum: name=httpd state=absent

- name: Manually enable remi repo
  ini_file: dest=/etc/yum.repos.d/remi.repo section=remi option=enabled value=1

- name: Update ALL yum packages to latest
  yum: pkg=* state=latest

- name: Install Yum packages needed for project
  yum: "pkg={{ item }} state=present"
  with_items:
  - openssh
  - openvpn
  - curl
  - curl-devel
  - gcc
  - gcc-c++
  - zip
  - unzip
  - mutt
  - make
  - libtool
  - binutils
  - openssl
  - git
  - gitflow
  - memcached
  - openssl-devel
  - vim-common
  - nodejs.x86_64
  - npm
  - ruby
  - ruby-rdoc
  - ruby-devel
  - rubygems
  - java-1.7.0-openjdk-devel
  - re2c
  - zeromq-devel
  - zeromq
  - php
  - php-fpm
  - php-common
  - php-pecl-apc
  - php-cli
  - php-pear
  - php-pdo
  - php-mysqlnd
  - php-pgsql
  - php-pecl-mongo
  - php-sqlite
  - php-pecl-memcache
  - php-pecl-memcached
  - php-gd
  - php-mbstring
  - php-mcrypt
  - php-xml
  - php-pecl-geoip
  - php-pecl-imagick
  - php-devel
  - pcre-devel
  - php-pecl-xdebug
  - mysql-server
  - MySQL-python
  - libselinux-python
  - libsemanage-python

- name: Clean up yum.
  command: yum clean all
